### ISSUE TITLE
Feature Request : .Ini/Json File Viewer/Editor.

### ISSUE THREAD

**Issue by Volti-p** [joel16/3DShell#44] opened 2019-02-01 21:53 UTC
It would be cool, if we can edit `.ini` Files and View it. But it would be cool too, if we can View .json files too and edit it. I would Appreciate it. :)

**Comment by joel16** [comment] 2019-04-26 15:04
Closing this as it is a duplicate of the other issue.

**Closed by joel16** 2019-04-26 15:04 UTC
